### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ScottChicken** [dhmay/jamstats#139]
**Describe the bug**
System failed - here are the messages:

**From the JamStats app:**
Thread 0x000074b0 (most recent call first):
  File "gevent\libuv\loop.py", line 556 in run
  File "gevent\hub.py", line 647 in run

**From the Chrome window:**
Traceback (most recent call last):
  File "flask\app.py", line 2531, in wsgi_app
  File "flask\app.py", line 2528, in wsgi_app
  File "flask\app.py", line 1825, in full_dispatch_request
  File "flask\app.py", line 1823, in full_dispatch_request
  File "flask\app.py", line 1799, in dispatch_request
  File "jamstats\web\statserver.py", line 260, in index
AttributeError: 'Flask' object has no attribute 'game_update_time'

**Screenshots**
Didn't capture any, I'm sorry to say, just hit "restart" in the app and reloaded the page

**Comment by dhmay** [comment]
Thanks. I'll use this issue to track all the issues related to crashing and the response to dropped proxy connections at the track. I'm glad "restart" is a workaround.

What behavior do you get in the browser? Does it cop to not being connected, before it goes down, or does the display just stop updating?

**Comment by dhmay** [comment]
Ah, good, I think I have a solution. The way I limped us through Clover Cup was the wrong solution; now I think I've got the right one.

**Comment by dhmay** [comment]
If you're feeling lucky, I think I've got a solution to the crashing problems when the proxy disconnects. Build in progress:
https://github.com/dhmay/jamstats/actions/runs/4590751514

**Comment by dhmay** [comment]
Reopen if you still have trouble with the new build.
